from __future__ import annotations

import re
from pathlib import Path
from typing import Literal

from .models import Transcript, TranscriptSegment, TranscriptWord


CaptionPreset = Literal["none", "clean", "bold_focus", "karaoke", "subtitle_box"]
Layout = Literal["portrait", "landscape", "smart_portrait", "gaming_portrait"]


def captions_disabled(preset: CaptionPreset) -> bool:
    return preset == "none"


def _ass_time(seconds: float) -> str:
    centiseconds = max(0, round(seconds * 100))
    hours, remainder = divmod(centiseconds, 360_000)
    minutes, remainder = divmod(remainder, 6_000)
    whole_seconds, fraction = divmod(remainder, 100)
    return f"{hours}:{minutes:02d}:{whole_seconds:02d}.{fraction:02d}"


def _escape_text(value: str) -> str:
    # Full-width braces/backslash prevent transcript content from injecting ASS
    # override tags while keeping the visible subtitle readable.
    return (
        value.replace("\\", "＼")
        .replace("{", "｛")
        .replace("}", "｝")
        .replace("\r", " ")
        .replace("\n", r"\N")
        .strip()
    )


def _group_words(words: list[TranscriptWord], layout: Layout) -> list[list[TranscriptWord]]:
    limit = 6 if layout in {"portrait", "smart_portrait", "gaming_portrait"} else 10
    groups: list[list[TranscriptWord]] = []
    current: list[TranscriptWord] = []
    for word in words:
        # Pauses up to 1.2s remain in the phrase; karaoke encodes that silence
        # explicitly so later words do not drift. Longer pauses start a new cue.
        if current and word.startSeconds - current[-1].endSeconds > 1.2:
            groups.append(current)
            current = []
        current.append(word)
        if len(current) >= limit or (len(current) >= 3 and re.search(r"[.!?][\"']?$", word.text)):
            groups.append(current)
            current = []
    if current:
        groups.append(current)
    return groups


def _line_broken(words: list[str], layout: Layout) -> str:
    if len(words) < 5:
        return " ".join(words)
    midpoint = len(words) // 2
    # Portrait captions stay within two balanced lines. Landscape groups have
    # enough width to remain on a single line unless they are unusually long.
    if layout == "landscape" and len(" ".join(words)) <= 58:
        return " ".join(words)
    return " ".join(words[:midpoint]) + r"\N" + " ".join(words[midpoint:])


def _clip_words(transcript: Transcript, clip_start: float, clip_end: float) -> list[TranscriptWord]:
    return [
        TranscriptWord(
            text=word.text,
            startSeconds=max(0.0, word.startSeconds - clip_start),
            endSeconds=max(0.0, min(clip_end, word.endSeconds) - clip_start),
        )
        for word in transcript.words
        if word.endSeconds > clip_start and word.startSeconds < clip_end
    ]


def _clip_segments(transcript: Transcript, clip_start: float, clip_end: float) -> list[TranscriptSegment]:
    return [
        TranscriptSegment(
            text=segment.text,
            startSeconds=max(0.0, segment.startSeconds - clip_start),
            endSeconds=max(0.0, min(clip_end, segment.endSeconds) - clip_start),
            words=[],
        )
        for segment in transcript.segments
        if segment.endSeconds > clip_start and segment.startSeconds < clip_end
    ]


def _header(preset: CaptionPreset, layout: Layout, dual: bool = False) -> str:
    portrait = layout in {"portrait", "smart_portrait", "gaming_portrait"}
    width, height = (1080, 1920) if portrait else (1920, 1080)
    font_size = 72 if portrait else 54
    # Dual facecam cards occupy the bottom 304px; lift the caption clear of them.
    margin_v = 360 if dual else (220 if portrait else 96)
    # The bundled Inter variable font contains the full weight axis. libass
    # selects the heavy instance through Bold=-1, so one deterministic font
    # asset covers both regular and ExtraBold caption styles.
    font = "Inter"
    bold = -1 if preset in {"bold_focus", "karaoke"} else 0
    border_style = 3 if preset == "subtitle_box" else 1
    outline = 0 if preset == "subtitle_box" else 4
    shadow = 0 if preset == "subtitle_box" else 2
    primary = "&H005F6BFF" if preset == "karaoke" else "&H00FFFFFF"
    secondary = "&H00FFFFFF" if preset == "karaoke" else "&H005F6BFF"
    back = "&H60000000" if preset == "subtitle_box" else "&H90000000"
    return f"""[Script Info]
; Generated by CutToClip. Timings are relative to the rendered clip.
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,{font},{font_size},{primary},{secondary},&H00181818,{back},{bold},0,0,0,100,100,0,0,{border_style},{outline},{shadow},2,64,64,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _dialogue(start: float, end: float, text: str) -> str:
    # A two-frame minimum prevents zero-duration events from being discarded.
    end = max(start + 0.04, end)
    return f"Dialogue: 0,{_ass_time(start)},{_ass_time(end)},Caption,,0,0,0,,{text}"


def _events_for_words(words: list[TranscriptWord], preset: CaptionPreset, layout: Layout) -> list[str]:
    events: list[str] = []
    accent = "&H005F6BFF&"
    for group in _group_words(words, layout):
        escaped = [_escape_text(word.text) for word in group]
        if preset in {"clean", "subtitle_box"}:
            events.append(_dialogue(group[0].startSeconds, group[-1].endSeconds, _line_broken(escaped, layout)))
            continue
        if preset == "karaoke":
            syllables: list[str] = []
            previous_end = group[0].startSeconds
            for word, text in zip(group, escaped, strict=True):
                gap = max(0, round((word.startSeconds - previous_end) * 100))
                duration = max(1, round((word.endSeconds - word.startSeconds) * 100))
                lead = (r"{\k" + str(gap) + r"}\h") if gap else ""
                syllables.append(lead + r"{\kf" + str(duration) + "}" + text)
                previous_end = word.endSeconds
            events.append(_dialogue(group[0].startSeconds, group[-1].endSeconds, _line_broken(syllables, layout)))
            continue

        # Bold Focus holds the full phrase on screen while coloring only the
        # currently spoken word. Each word event ends at the next word so there
        # is no flicker between adjacent timestamps.
        for index, word in enumerate(group):
            rendered: list[str] = []
            for word_index, text in enumerate(escaped):
                if word_index == index:
                    rendered.append(r"{\c" + accent + r"\b1}" + text + r"{\rCaption}")
                else:
                    rendered.append(text)
            event_end = group[index + 1].startSeconds if index + 1 < len(group) else word.endSeconds
            events.append(_dialogue(word.startSeconds, event_end, _line_broken(rendered, layout)))
    return events


def _events_for_segments(segments: list[TranscriptSegment], layout: Layout) -> list[str]:
    events: list[str] = []
    for segment in segments:
        words = [_escape_text(item) for item in segment.text.split()]
        if not words:
            continue
        # Segment-only responses cannot support true active-word timing, but
        # they still render honest segment timestamps rather than fake timing.
        events.append(_dialogue(segment.startSeconds, segment.endSeconds, _line_broken(words, layout)))
    return events


def build_ass(
    transcript: Transcript,
    clip_start: float,
    clip_end: float,
    preset: CaptionPreset,
    layout: Layout,
    output_path: str | Path,
    dual: bool = False,
) -> Path:
    if clip_end <= clip_start:
        raise ValueError("clip_end must be greater than clip_start")
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    words = _clip_words(transcript, clip_start, clip_end)
    events = _events_for_words(words, preset, layout) if words else _events_for_segments(
        _clip_segments(transcript, clip_start, clip_end), layout
    )
    output.write_text(_header(preset, layout, dual) + "\n".join(events) + "\n", encoding="utf-8-sig")
    return output


def ass_filter(path: str | Path, font_dir: str | Path | None = None) -> str:
    def escape(value: str | Path) -> str:
        normalized = Path(value).resolve().as_posix()
        return normalized.replace("'", r"\'").replace(":", r"\:").replace(",", r"\,")

    expression = f"ass=filename='{escape(path)}'"
    if font_dir and Path(font_dir).exists():
        expression += f":fontsdir='{escape(font_dir)}'"
    return expression
